### ISSUE TITLE
ReactiveSequence 🚗🚕🚙

### ISSUE THREAD

**Issue by dmcrodrigues** [RACCommunity/contributors#3]
Being able to observe a sequence can be extremely handy in a few use-cases, e.g. determining what should be inserted, deleted or reloaded in a `UITableView`. We should have a reactive structure to complete our toolbox.

**Comment by RuiAAPeres** [comment]
So this implementation would support what protocols? I had the following in mind:
1. `MutableCollectionType`
2. `CollectionType`
3. `CustomStringConvertible`

Perhaps:
1. `RangeReplaceableCollectionType`

**Edit:** Looking at what an `Array` adopts (assuming this is what we will use as back storage) it should probably need to conform with [these](https://developer.apple.com/library/watchos/documentation/Swift/Reference/Swift_Array_Structure/index.html#//apple_ref/swift/struct/s:Sa).

**Comment by RuiAAPeres** [comment]
Maybe @carlossless has some ideas. 👍

**Comment by liscio** [comment]
There's some great stuff that @neilpa has been exploring in this branch along these lines: https://github.com/neilpa/Rex/pull/53

**Comment by liscio** [comment]
…and if we can somehow combine the above with this work (https://realm.io/news/slug-jad-osseiran-protocol-extension-list-controller) then we can really launch folks forward on the "feeding collection/table views" front.

**Comment by RuiAAPeres** [comment]
@liscio  acting a bit as a devil's advocate: aren't we trying to make this overly complex. In this case "complex" is not actually the right word, maybe "abstract"? (looking at how transducers work). In this case we are just focused in a sequence, I think transducers would make sense to unite all the types around common operations: using the same `map` for a `SignalProducer`, `Signal` and finally this "ReactiveArray". 

What do you think @dmcrodrigues?

**Comment by carlossless** [comment]
I'm currently working on my own RACUI implementation that incorporates UITableView and UICollectionView datasource/delegate bindings. I find that this implementation of [ReactiveArray](https://github.com/Wolox/ReactiveArray/blob/master/ReactiveArray/ReactiveArray.swift) works fairly well for this use case.

**Comment by RuiAAPeres** [comment]
@carlossless two questions:
1. Do you think it would make sense to have our own lib, maintained by us?  (ReactiveArray last commit was in March)
2. What about doing the `RACUI` in the context of this org?

**Comment by carlossless** [comment]
1. Yes I think it does, but I don't know whether we should rewrite it, or just ask them to maybe incorporate it here? (¯_(ツ)_/¯)
2. If anyone more capable doesn't do it first, sure I'd love to collaborate. However I would like to finish the core and battle test it in at least one of my own apps before publishing it, let alone publishing it here.

**Comment by RuiAAPeres** [comment]
1. I find that difficult to happen, since it's associated with a company. I think @dmcrodrigues will do a brilliant job, kicking this off. 
2. Why not doing in the open? I think it would benefit a lot (not doubting you will do a terrific work on your own!). Since you would start it, you will be stewarding it. 👍 A lot of people, me included, would benefit from it as well.

**Comment by andersio** [comment]
Not sure if you guys are interested, but you may have a look at my toolbox.

~~I have a `ReactiveSet` + `ReactiveSetSection` (both inherited from `BidirectionalCollection`) family of protocols there.~~ On top of the protocols, there are type erased wrappers to facilitate collection mapping between the model layer and the view model layer.

It [works like this illustrative gist](https://gist.github.com/andersio/0ab044bdc3b4426ee87b4337c7e16bb3).

https://github.com/andersio/MantleData/tree/master/MantleData
(Note that it has Core Data extensions & some experimental stuff too, hmm)

That's said not everything is polished, and I haven't written any tests for it yet. ~~(Spent too much time reinventing `NSFetchedResultsController` and BOOM Apple said it is on Mac now)~~

**Comment by andersio** [comment]
Hmm... I am experimenting with the idea of a `NestableCollection` protocol (and `IndexPath`) which should provide an abstraction of whatever level of nested collection.

**Comment by RuiAAPeres** [comment]
@andersio that's some pretty nice work, specially the gist example, love it! ♥️ In any case, I would like for @dmcrodrigues to finish the work with its own implementation, since he was the one who proposed it. Once we got a v1.0, we will iterate over it, with your ideas. 

What do you think?

**Comment by andersio** [comment]
Of course. 👍

**Comment by RuiAAPeres** [comment]
Currently being addressed @ [RACCommunity/ReactiveCollections](https://github.com/RACCommunity/ReactiveCollections)
