### ISSUE TITLE
RAC with <~ operator overloading

### ISSUE THREAD

**Issue by bibekdari** [RACCommunity/contributors#6]
Hi, I have tried a ReactiveCocoa4 and MVVM pattern in a simple swift project. Can anyone verify my way of doing is it right or wrong also suggest me for improvements?
this is github link for the project:
https://github.com/bibekdari/ReactiveCocoa4MVVMPerson
Thank you! :)

**Comment by mdiep** [comment]
I would took a look at using https://github.com/neilpa/Rex. That should make things easier and more idiomatic. The Rex code will be a part of RAC 5. (Likely with some minor adjustments.)
